version: "3.8"

services:
  rafly-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rafly-app-next-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: pnpm dev
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
